### ISSUE TITLE
楼主给力

### ISSUE THREAD

**Issue by douyahu** [wkunzhi/rbac-stark-crm#2]
为了搞这个权限相关，选用了xadmin+guardian+django2.0 
1. 结果发现django2.0不支持oracle11， 降级
2. 再发现xadmin和guardian兼容有问题，摒弃guardian
3. 使用rules，发现使用动态多数据库时，xadmin扩展性尴尬，摒弃
4. 最后github一个一个找，找到楼主这个，扩展性强，真心强大，唯一不足的就是django1.11需要gi该代码，不过问题不大，提臀感谢楼主！！！！

**Comment by wkunzhi** [comment]
感谢支持
