### ISSUE TITLE
怎么控制菜单的顺序

### ISSUE THREAD

**Issue by jimmy14k** [wkunzhi/rbac-stark-crm#3]
录入过的菜单，怎么再次调整一、二级菜单的排列顺序呢

**Comment by douyahu** [comment]
我留意了下，目测是没有办法，数据库里也没有排序结构，需要自己修改

**Comment by wkunzhi** [comment]
已录入的，一级不能调整到下级

**Comment by douyahu** [comment]
我这里改了楼主的代码，修改了数据库字段，添加了录入配置，后续，有时间我将这块上传下！
![image](https://user-images.githubusercontent.com/47881587/65576336-5b3f0c80-dfa4-11e9-8f25-1ec568505dac.png)

**Comment by wkunzhi** [comment]
欢迎push

**Comment by jimmy14k** [comment]
@douyahu @wkunzhi 感谢
